<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find icube_description)/urdf/include/common_properties.urdf.xacro" />
  <!-- <xacro:include filename="$(find icube_description)/urdf/include/icube_chassis.gazebo.xacro" /> -->
  <!-- <xacro:include filename="$(find icube_description)/urdf/include/icube_chassis.transmission.xacro" /> -->
	<xacro:include filename="$(find icube_description)/urdf/include/sick_tim571.urdf.xacro" />

	<xacro:property name="deg_to_rad" value="0.017453293" />

	<!-- icube physical properties -->
	<xacro:property name="icube_chassis_mass" value="30.0" />

	<!-- icube actuated wheel (iwheel) -->
	<xacro:property name="icube_act_wheel_radius" value="0.077" />
  <xacro:property name="icube_act_wheel_width" value="0.04" />
  <xacro:property name="icube_act_wheel_mass" value="0.76" />
  <xacro:property name="icube_act_wheel_dx" value="0.0" />
  <xacro:property name="icube_act_wheel_dy" value="0.1845" />

	<!-- caster wheel physical properties -->
	<xacro:property name="icube_caster_wheel_radius" value="0.025" />
  <xacro:property name="icube_caster_wheel_width" value="0.0219" />
  <xacro:property name="icube_caster_wheel_mass" value="0.2" />
  <xacro:property name="icube_caster_wheel_dx" value="-0.005" />
  <xacro:property name="icube_caster_wheel_dy" value="0" />
  <xacro:property name="icube_caster_wheel_dz" value="-0.094" />

	<!-- caster hub/base physical properties -->
  <xacro:property name="icube_front_caster_wheel_base_dx" value="0.20045" />
  <xacro:property name="icube_back_caster_wheel_base_dx" value="-0.20045" />
  <xacro:property name="icube_caster_wheel_base_dy" value="0.165" />
  <xacro:property name="icube_caster_wheel_base_dz" value="${icube_caster_wheel_radius-icube_caster_wheel_dz}" />

	<!-- actuated wheel definition-->
	<xacro:macro name="actuated_wheel" params="locationprefix locationright">

		<!-- actuated wheel joint -->
    <joint name="${locationprefix}_wheel_joint" type="continuous">
      <origin xyz="0.0 ${-icube_act_wheel_dy * locationright} ${icube_act_wheel_radius - 0.0025}" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="${locationprefix}_wheel_link" />
      <axis xyz="0 1 0" />
      <!-- <limit effort="100" velocity="180.0" /> -->
    </joint>

		<!-- actuated wheel link -->
    <link name="${locationprefix}_wheel_link">
      <xacro:cylinder_inertial mass="${icube_act_wheel_mass}" radius="${icube_act_wheel_radius}" length="${icube_act_wheel_width}">
        <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
      </xacro:cylinder_inertial>
      <visual>
        <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
        <geometry>
          <mesh filename="$(find icube_description)/meshes/wheel.dae" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
        <geometry>
          <mesh filename="$(find icube_description)/meshes/wheel.dae" />
        </geometry>
      </collision>
    </link>
  </xacro:macro>

	<!-- caster hub/base and caster wheel definition -->
	<xacro:macro name="caster_wheel" params="locationprefix locationright wheel_base_dx">

    <!-- caster hub/base joint -->
    <joint name="${locationprefix}_caster_rotation_joint" type="continuous">
      <origin xyz="${wheel_base_dx} ${-icube_caster_wheel_base_dy * locationright} ${icube_caster_wheel_base_dz}" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="${locationprefix}_caster_rotation_link" />
      <axis xyz="0 0 1" />
      <!-- <dynamics damping="0.01" friction="0.0"/> -->
    </joint>

		<!-- caster hub/base link -->
    <link name="${locationprefix}_caster_rotation_link">
      <inertial>
        <origin xyz="0 0 -0.042500000044" rpy="${24 * deg_to_rad} 0 ${0.5 * pi} " />
        <mass value="0.3" />
        <inertia
          ixx="0.0005844517978"
          ixy="0"
          ixz="0"
          iyy="0.00052872551237"
          iyz="0"
          izz="0.00017923555074" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <cylinder length="0.1" radius="0.01"/>
        </geometry>
      </visual>
    </link>

    <!-- caster wheel -->
    <joint name="${locationprefix}_caster_wheel_joint" type="continuous">
      <origin xyz="${icube_caster_wheel_dx} ${-icube_caster_wheel_dy * locationright} ${icube_caster_wheel_dz}" rpy="0 0 0" />
      <parent link="${locationprefix}_caster_rotation_link" />
      <child link="${locationprefix}_caster_wheel_link" />
      <axis xyz="0 1 0" />
    </joint>

    <link name="${locationprefix}_caster_wheel_link">
      <xacro:cylinder_inertial mass="${icube_caster_wheel_mass}" radius="${icube_caster_wheel_radius}" length="${icube_caster_wheel_width}">
        <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
      </xacro:cylinder_inertial>
      <visual>
        <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
        <geometry>
          <mesh filename="$(find icube_description)/meshes/caster.dae" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
        <geometry>
          <mesh filename="$(find icube_description)/meshes/caster.dae" />
        </geometry>
      </collision>
    </link>

    <!-- <gazebo reference="${locationprefix}_caster_wheel_link">
    </gazebo> -->
  </xacro:macro>

  <!--####################################################################-->
	<!-- icube base -->
	<xacro:macro name="icube">
		<!-- base footprint-->
    <link name="base_footprint" />

    <joint name="base_joint" type="fixed">
      <parent link="base_footprint" />
      <child link="base_link" />
      <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

		<!-- base link -->
    <link name="base_link">
			<!-- base link inertial from box -->
      <xacro:box_inertial mass="${icube_chassis_mass}" x="0.498" y="0.453" z="0.273">
        <origin xyz="${icube_act_wheel_dx} 0 0.04218" rpy="0 0 0" />
      </xacro:box_inertial>

      <visual>
        <origin xyz="${icube_act_wheel_dx} 0 0.04218" rpy="0 0 0" />
        <geometry>
          <mesh filename="$(find icube_description)/meshes/chassis.dae" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="${icube_act_wheel_dx} 0 0.04218" rpy="0 0 0" />
        <geometry>
          <mesh filename="$(find icube_description)/meshes/chassis.dae" />
        </geometry>
      </collision>
    </link>

    <!-- Laser scanners -->
    <joint name="base_link_to_front_laser_joint" type="fixed">
      <parent link="base_link" />
      <child link="front_laser_link" />
      <origin xyz=".21746 0 0.273" rpy="0 0 0" />
    </joint>
    <xacro:sick_tim571 link="front_laser_link" topic="scan" />

    <!-- actuated wheels -->
    <xacro:actuated_wheel locationprefix="left" locationright="-1"/>
    <xacro:actuated_wheel locationprefix="right" locationright="1"/>

		<!-- caster wheels -->
    <xacro:caster_wheel locationprefix="fl" locationright="-1" wheel_base_dx="${icube_front_caster_wheel_base_dx}"/>
    <xacro:caster_wheel locationprefix="fr" locationright="1" wheel_base_dx="${icube_front_caster_wheel_base_dx}"/>
    <xacro:caster_wheel locationprefix="bl" locationright="-1" wheel_base_dx="${icube_back_caster_wheel_base_dx}"/>
    <xacro:caster_wheel locationprefix="br" locationright="1" wheel_base_dx="${icube_back_caster_wheel_base_dx}"/>

    <joint name="base_link_surface_joint" type="fixed">
      <origin xyz="${icube_act_wheel_dx} 0 0.315" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="surface" />
      <axis xyz="0 0 1" />
    </joint>

    <link name="surface"/>

    <gazebo>
      <plugin name='diff_drive' filename='libgazebo_ros_diff_drive.so'>
        <ros>
          <namespace>/demo</namespace>
        </ros>
  
        <!-- wheels -->
        <left_joint>left_wheel_joint</left_joint>
        <right_joint>right_wheel_joint</right_joint>
  
        <!-- kinematics -->
        <wheel_separation>${icube_act_wheel_dy*2}</wheel_separation>
        <wheel_diameter>${icube_act_wheel_radius*2}</wheel_diameter>
  
        <!-- limits -->
        <max_wheel_torque>20</max_wheel_torque>
        <max_wheel_acceleration>1.0</max_wheel_acceleration>
  
        <!-- output -->
        <publish_odom>true</publish_odom>
        <publish_odom_tf>false</publish_odom_tf>
        <publish_wheel_tf>true</publish_wheel_tf>
  
        <odometry_frame>odom</odometry_frame>
        <robot_base_frame>base_link</robot_base_frame>
      </plugin>
    </gazebo>
    <!-- <xacro:icube_wheel_transmissions/> -->

    <!-- set the gazebo friction parameters for the wheels -->
    <!-- <xacro:set_all_wheel_frictions/> -->

  </xacro:macro>
</robot>